vifm/vifm

COPYING
The COPYING file states an old version of the GPLv2.
I updated the file with the latest version.
The legal part itself do not change. It's just about updating the adress
of the FSF and some things like "19yy" to "year".
However there seem to be some nonvisual character changes in that file
too. Nevertheless I it is the offical version available at
https://www.gnu.org/licenses/gpl-2.0.txt that I added here.
=> Updating license file

data/man/vifm.1, data/vim/doc/app/vifm-app.txt, src/utils/utils_nix.c
I've added the possibility to set the `slowfs` option to `"*"`. This means that all directories are treated as slow. I did this because on `cygwin`, calling the `traverse_mount_points` and `start_with_list_item` function every second is very slow. 
So even if I am on a slow file system, and the system is included in the `slowfs` option, the overall experience is extremely poor. Setting the `slowfs` to `"*"` makes all the difference. `vifm` becomes usable also under `cygwin`.
There is also the possibility to check at a compile time with the preprocessor that `vifm` is running in `cygwin` and disable the `slowfs`, but maybe there are people who want to use it even slow under `cygwin`. So to me, this seems like the better option.
=> Added * for slowfs

src/modes/dialogs/change_dialog.c, src/modes/dialogs/sort_dialog.c
I added shortcuts for dialog options, because I often toggle between sort orders.
Thus with the default mapping of **S** to open the sort dialog:
* **Ss** sorts pane items by size
* **Se** sorts pane items by extension
* **SN** sorts pane items by name, ignoring case
* And so on...
For completeness I also added [shortcuts to the change dialog](https://github.com/oo-/vifm/blob/76fe047f9880d618710cf6a375a43bdee6042c25/src/modes/dialogs/change_dialog.c#L134). Shortcuts did not seem relevant for msg or attr dialogs.
I tried to preserve the style of existing code and UI. I did not add any tests because I didn't understand vifm's testing scheme.
=> Dialog shortcuts

.travis.yml, tests/Makefile
Hi,
I'm trying to enable OS X checks on Travis CI. I fixed non-compatible sed (not supporting {...} ).
It's still failing on unit tests, can you help me?
Thanks
=> Travis OS X

data/vifmrc
sxiv is efficient when handling many images. Take advantage of this when selecting multiple image files in vifm.
=> Open all selected files with sxiv

AUTHORS, ChangeLog, THANKS, src/filelist.c, src/fops_rename.c, src/utils/fs.c, tests/fileops/rename_files.c
The file browser has the nice ability of changing the current working
directory to the currently displayed one. That changing happens
depending on which view is active, i.e., the left or the right side.
Unfortunately, if there are updates happening on the other side, for
example because a file increased its size, the current working directory
will be changed and not reverted as part of the view update process.
That is a problem when spawning off a new shell and expecting it to have
its working directory set to the currently active view's one.
This change fixes the problem by correctly restoring the current working
directory after each update operation.
=> Correctly change back current directory after view update

ChangeLog, src/utils/utils_nix.c
Make it consistent with what `df` reports.
=> Fix reported free space on *nix

AUTHORS, ChangeLog, data/man/vifm.1, data/vim/doc/app/vifm-app.txt, src/ui/statusline.c, tests/misc/expand_status_line_macros.c
The syntax is: `%{...}`. E.g. `%{&sort}` evaluates to the value of the
`sort` option.
Resolves https://github.com/vifm/vifm/issues/304
=> Add support for arbitrary exps in statusline

data/man/vifm.1, data/vim/doc/app/vifm-app.txt, src/cfg/config.c, src/cfg/info.c, src/opt_handlers.c, src/ui/fileview.c
I still fail to understand why it was put there in the first place.
=> Remove the leading space from timefmt

src/event_loop.c
When vifm is started and it is configured to restore the previous
directory state (via set vifminfo=...,dhistory,savedirs,...), it will
set the program's current working directory according to that state.
However, the working directory ultimately set last is that of the right
file view, while the actually active file view is that on the left. That
causes confusion when forking off another program that will now have the
wrong working directory set.
To fix this problem this change reorders the auto-command triggering
code to first happen for the right view and only then for the left one.
=> Set correct working directory on startup

data/vifmrc
Hi and thanks a lot for vifm!
The change simplifies the command to preview images and makes the output less redundant.
Instead of
example.png PNG 1366x768 1366x768+0+0 8-bit sRGB 176847B 0.030u 0:00.026
example.png=>/dev/null PNG 1366x768 1366x7 68+0+0 8-bit sRGB 176847B 0.200u 0:00.130
the output's now
examlpe.png PNG 1366x768 1366x768+0+0 8-bit sRGB 176847B 0.000u 0:00.000
=> Simplify image preview

src/trash.c, src/vifm.c
* Create trash directory only if user wants it.
* If file system is read-only, do not warn about non-creatable trash.
=> Fix trash directory annoyances

src/menus/media_menu.c, src/ui/ui.c, tests/misc/integration.c, tests/misc/menus_media.c
- Spawn media program in foreground,
- Show decorators for devices and mount-points,
- Make actions to be more human-friendly in regards of selected item,
- Accept `info=` for showing arbitrary text next to devices,
- Add [, ] keybindings for navigating between devices,
- Show blank lines only if there is enough space for them.
I didn't want to pollute the code with new commands like "eject"/"detach"/"power off" with random keybindings, instead user can extend her media program and implement these functionalities in that.
So running it in foreground solves this and my password input issues too.
I kept blank lines only if there is enough rows, so they won't be annoying if other devices go off-screen because of them; otherwise they help visually separating devices (as before). Plus, I added …
=> Improve media menu

data/man/vifm.1, src/cfg/config.c, src/cfg/config.h, src/opt_handlers.c, src/utils/utils.c, tests/fileops/suite.c, tests/misc/expand_status_line_macros.c, tests/misc/options.c, tests/utils/friendly_size.c
Makes inserted space optional when formatting sizes, ie. `9.2 M` => `9.2M`.
=> Add "nospace" key to 'sizefmt' option

src/ui/fileview.c, src/ui/ui.c, src/ui/ui.h
Time was only needed to provide a monotonic counter, but if I'm right, simple boolean flags can get the job done, too.
=> Simplify postponed view updating

src/ui/ui.c
Hi,
Thank you for awesome vifm.
Here is a PR for issue https://github.com/vifm/vifm/issues/634 - if you find it useful.
thx,
-m
=> Disable extended keys above KEY_MAX so that esc-codes can be used in mappings

data/man/vifm.1, data/vim/doc/app/vifm-app.txt, src/modes/dialogs/attr_dialog_nix.c
I implemented keybindings to set/unset all the bits of a same class in the permission dialog (as requested #659). Namely, `r` sets/unsets all the r bits, and so on. Also `e` checks the "Set Recursively" flag.
I added some comments in some other parts of the file. Since I did not notice comments in that file, feel free to remove them, but I think they are somehow helpful.
Let me know in case there is something I overlooked or that I can improve. I have neither access to nor familiarity with Windows so those are for Unix only.
=> Add keybindings to permissions dialog

data/man/vifm.1, data/vim/doc/app/vifm-app.txt, src/macros.c, src/macros.h, src/running.c, tests/misc/expand_macros.c
Vifm has the `%s` macro, but this always splits horizontally. For a vertically split window, I propose `%v`.
I have tested the patch both in Screen and Tmux. 
Let me know if there is something I can improve. Cheers!
=> Add %v for vertical multiplexer split

data/man/vifm.1, data/vim/doc/app/vifm-app.txt, src/cfg/config.c, src/cfg/config.h, src/opt_handlers.c, src/ui/quickview.c, src/vcache.c, tests/misc/options.c, tests/misc/view_dir.c
This is meant to address issue #514 with a new boolean option, `countfirst`, which allows one to move the count of directory and non-directory files to the top of the quick view when listing a directory. 
Handling the cache part was a bit challenging for me, so, as usual, please let me know if there is something to improve. Cheers!
=> Allow file count before tree in quickview

data/vifmrc
When opening files in Windows10 by hitting enter, I get a noticeable lag even for 1KB text file which doesn't happen when opening from Windows Explorer. This happens with stock vifmrc only on Windows10 but not on Windows7.
Also when opening a file the console window goes blank (black console background is shown when vifm was running) on both win10 and win7.
Adding `%"f &` after explorer in the option fixes both the aforementioned problems for me in Win7 and Win10.
Thanks for making vifm and making it available for Windows!
=> Updated vi[x]cmd for Windows

data/vifmrc
I added zstd support for `archivemount` and zstd preview, fixed preview for `*.tar.xz,*.txz` archives.
What do you think? If you need to change something, the branch is editable.
=> Minore additions and fixes for archivemount filetypes

src/compare.c, src/filtering.c, src/filtering.h, src/utils/filter.c, src/utils/filter.h
I think there is no need to update documentation this time since it already says
> Filtered files are not checked in / search or :commands.
Closes #683.
=> Make :compare honor filters

src/int/file_magic.c
According to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html),
> $XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.
=> Use $XDG_DATA_HOME

data/man/vifm.1, data/vim/doc/app/vifm-app.txt, src/cfg/config.c, src/cfg/config.h, src/cfg/info.c, src/opt_handlers.c, src/ui/ui.c, tests/misc/options.c, tests/test-support/test-utils.c
This is meant to close #712.
If you like it, I will document it.
Besides hborder, the main changes are:
1. `vborder=""` is treated equally to `vborder =" "` in `clear_border`.
2. No longer "hide" vborder from `set fillchars?` when it is null or a space. I think doing otherwise would unnecessarily complicate the code, but let me know if it's shortsight.
=> Add hborder

src/bracket_notation.c
Thank you so much for vifm.
Another method could be to instead call:
keyok(KEY_SF, FALSE);
etc. for each of these curses defined shifted keys in setup_ncurses_interface() in ui/ui.c
But that would then mean mappings don't use the name such as \<s-down\> but the actual multi-char escape codes.  Not sure which method seems better ?
We could also wrap each in an ifdef to make sure they are defined before using, if needed.
=> add the curses supported shift key definitions so they can be mapped

data/shell-completion/fish/vifm.fish, src/Makefile.am
Completion for '+' argument is not implemented as I can't figure out how to do so. Help is welcomed.
=> Add shell completion for fish-shell

data/vifmrc
I didn't check viewing of `*.jar | *.war | *.ear | *.oxt`, but googling says that it should be works. `*.zip` viewing is works.
If trying view `*.zip` with tar, it will be print `tar: This does not look like a tar archive`
=> Fix zip fileviewer in vifmrc

ChangeLog, data/man/vifm.1, data/vim/doc/app/vifm-app.txt, src/cmd_completion.c, src/cmd_handlers.c, src/compare.c, src/compare.h, src/modes/modes.c, src/ui/ui.c, src/ui/ui.h, tests/commands/misc.c, tests/commands/tabs.c, tests/misc/compare.c, tests/misc/compare_misc.c, tests/misc/diff.c, tests/misc/flist_misc.c
Added toggled `showidentical | showdifferent | showuniqueleft | showuniqueright` arguments for :compare command. If current view is `cv_compare` then arguments will be toggled with existed before comparing.
Now applying of them is restarting comparing. I don't know which is better. May be result of `flist_custom_put` calls can be saved to self-erased (on exit from compare view) structure, but I doubt.
Also disabled printing stats for `ofone` mode by moving `single_pane` to `CompareFlags`
=> Comparison results selecting

src/lua/vlua.c, src/lua/vlua.h, src/plugins.c, tests/lua/plugins.c
Hi, with the latest `--plugins-dir` option, I found vifm will always load plugin under `cfg.config_dir` (in my case, it is `$HOME/.config/vifm/plugins`), but it should respect the `plug->real_path`.
So I made this quick fix without looking too deep into the source.
todo:
* is the name param still necessary? since we get full_path from `plug->real_path` now
* add a test
=> Fix incorrect plugin loading path

data/vifmrc
I copied xclip keybinds from [this](https://wiki.vifm.info/index.php/How_to_copy_path_to_current_file/directory_to_system_clipboard) article to my config and realised that two keybinds (path yank ones) are already there but not working. 
Added `-n` argument to `echo` and `-selection clipboard` to `xclip`.
=> Fix xclip keybinds

data/plugins/editor/helix.lua, data/plugins/editor/init.lua
Allows using [Helix](https://github.com/helix-editor/helix/) as the default editor, `open-help` and `edit-list` handlers are not implemented.
Closes: https://github.com/vifm/vifm/issues/925
See also: https://github.com/helix-editor/helix/discussions/5902
=> Add helix handler to editor plugin

data/vifmrc
sweethome3d can only open one file with a full path.
=> Add Sweet Home 3D and missing asterisks

data/plugins/ueberzug/init.lua
`#ueberzug#image` can't generate thumbnail for Gif files.
So, I added explanation for two possible choices:
- Having animated previews by passing the gif file directly to `ueberzugpp` with `#ueberzug#image_no_cache`
- Or having the usual previews with `ueberzug` which uses the `#ueberzug#video` function instead.
=> Fix ueberzug usage example for Gif files

src/utils/utils_nix.c
FreeBSD needs same fix as OS X. See
https://man.freebsd.org/cgi/man.cgi?query=statvfs&sektion=3&n=1
=> Fix get_drive_info on FreeBSD

data/plugins/ueberzug/init.lua
Sometimes the file is actually `mp4`, but the extension is `gif`, which will cause the previewer to not work correctly. It's better not to rely on extensions when possible.
=> Fix Ueberzug gif example

data/man/vifm.1, src/ui/column_view.c, src/ui/column_view.h, src/utils/str.c, src/utils/str.h, src/viewcolumns_parser.c, tests/column_view/align.c, tests/column_view/cropping.c, tests/column_view/utf8.c
I often find myself working with files that have long names and for which the beginning and end part is important. I implemented this as an alignment option, which is like left alignment but cuts off the middle part if the name is too long:
Closes #868
=> Cut the middle part of a long filename

AUTHORS, BUGS, ChangeLog, src/ui/column_view.c, src/ui/column_view.h, src/ui/fileview.c, src/utils/str.c, src/utils/str.h, tests/column_view/align.c, tests/column_view/callbacks.c, tests/column_view/cropping.c, tests/column_view/general.c, tests/column_view/highlighting.c, tests/column_view/literals.c, tests/column_view/suite.c, tests/column_view/test.h, tests/column_view/utf8.c, tests/column_view/width.c, tests/misc/flist_misc.c, tests/test-support/test-utils.c
I have moved the code for adjusting the search match ranges closer to where the line is cut and decorated. I fixed the issues I noticed at the beginning, but if there are still issues I didn't notice or you have change suggestions, let me know.
=> Fix search match highlighting issues with handling lines with hidden parts

data/colors/Default-256.vifm
I just added them in the form that I am seeing in the GitHub editor.
=> Add zstd and tzst to Default-256.vifm

AUTHORS, ChangeLog, src/engine/cmds.c, tests/cmds/foreign.c
Hi, this tries to fix #973.
after this PR, I believe another relevant problem is `:com <tab>`, to be specific, the completion of `:com` should show FOREIGN_CMDs too.
=> Fix :com {cmd} not recognizes FOREIGN_CMDs

src/utils/utils_nix.c
Currently, at least with bash and zsh, vifm is unable to run a command whose name starts with a dash (`-`) inside of a `term()` or `system()` call:
zsh: bad option string: '-fd-compgen <...>'
Fix this by applying the idiomatic `--` guard to the shell invocation (by convention and by POSIX, `--` denotes end of options).
=> Fix handling of external commands starting with `-`

src/event_loop.c, tests/misc/event_loop.c
hi, while trying to figure out a way for #1007, i found that `<c-z>` has been hard-coded in event_loop::get_char_async_loop.
after read the context of get_char_async_loop, i think there is no particular reason to object  on making ctrl-z remappable in user land, so i made this PR.
the real usecase is that i have a plugin which runs vifm in a neovim's terminal buffer, and i want to add a keymap to vifm that informs nvim to hide the terminal buffer. as a proof of concept, i have already made this 'hidding functionality' work with [lhs-<space>.](https://github.com/haolian9/reveal.nvim/blob/master/lua/reveal/vifm/reveal/init.lua#L104).
=> make ctrl-z remappable in user land

data/vifm.appdata.xml
It should be in valid rDNS format:
https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic
Fixes:
```
$ appstreamcli validate vifm.appdata.xml
W: info.vifm:3: cid-desktopapp-is-not-rdns info.vifm
...
```
Also fix the incorrect "screenshot" tag:
```
I: info.vifm.vifm:16: unknown-tag screenshot
```
=> Fix AppStream metadata id and screenshot tag

data/man/vifm.1
Hi, I'm the maintainer of the vifm package in Debian and I noticed some typos and warnings in the manual using the Lintian tool. Have a good day!
=> vifm.1: Fix typos/warnings
